COO/Controllers/ContatoController.cs
using System.Web.Mvc;

namespace COO.Controllers
{
    public class ContatoController : Controller
    {
        // GET: Contato

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

COO/Controllers/DashboardController.cs
using Servico.Tabelas;
using System;
using System.Web.Mvc;

namespace COO.Controllers
{
    public class DashboardController : Controller
    {
        private DashboardServico dashboardServico = new DashboardServico();
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ObterDados()
        {
            ViewBag.QtdOcorrencias = dashboardServico.ObterQuantidadeOcorrenciaStatusAberto();

            return Json(ViewBag.QtdOcorrencias, JsonRequestBehavior.AllowGet);
        }

    }
}

COO/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COO.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

COO/Controllers/OcorrenciaController.cs
using Modelo.Entidades;
using Servico.Entidades;
using Servico.Tabelas;
using System;
using System.Net;
using System.Web.Mvc;

namespace COO.Controllers
{
    public class OcorrenciaController : Controller
    {
        private OcorrenciaServico ocorrenciaServico = new OcorrenciaServico();
        private IteracaoOcorrenciaServico iteracaoServico = new IteracaoOcorrenciaServico();

        // Métodos do Controlador Ocorrencia
        private ActionResult GravarOcorrencia(Ocorrencia ocorrencia)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ocorrencia.NumeroOcorrencia = ocorrenciaServico.GerarNumeroOcorrencia();
                    ocorrencia.StatusOcorrencia = 0;
                    ocorrencia.DataHora = DateTime.Now;
                    ocorrenciaServico.GravarOcorrencia(ocorrencia);
                    return RedirectToAction("ConsultarOcorrencia");
                }
                return View(ocorrencia);
            }
            catch
            {
                return View(ocorrencia);
            }
        }

        private ActionResult ObterVisaoOcorrenciaPorId(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ocorrencia produto = ocorrenciaServico.ObterOcorrenciaPorId((long)id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Ocorrencia
        [HttpGet]
        public ActionResult ConsultarOcorrencia()
        {
            return View(ocorrenciaServico.ObterOcorrenciasClassificadasPorDataHora());
        }

        // GET: Ocorrencia/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdicionarOcorrencia()
        {
            return View();
        }

        // POST: Ocorrencia/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdicionarOcorrencia(Ocorrencia ocorrencia)
        {
            if (ocorrencia != null)
            {
                return GravarOcorrencia(ocorrencia);
            } else
            {
                 return HttpNotFound();
            }
        }

        //	GET:	Servidor/Details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DetalharOcorrencia(long? id)
        {
            return ObterVisaoOcorrenciaPorId(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ListarIteracoes(long? Id)
        {
            var iteracoes = iteracaoServico.ObterIteracoes(Id);
            return Json(iteracoes, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public ActionResult AdicionarIteracoes(IteracaoOcorrencia iteracao)
        //{

        //    return iteracaoServico.GravarIteracao(iteracao);

        //}

    }
}

COO/Controllers/RotinaController.cs
using System.Web.Mvc;

namespace COO.Controllers
{
    public class RotinaController : Controller
    {
        // GET: Rotina
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

COO/Controllers/ServidorController.cs
using Modelo.Entidades;
using Servico.Entidades;
using System;
using System.Net;
using System.Web.Mvc;

namespace COO.Controllers
{
    public class ServidorController : Controller
    {
        private ServidorServico servidorServico = new ServidorServico();

        //Métodos do Controlador Servidor
        private ActionResult ObterVisaoServidorPorId(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servidor produto = servidorServico.ObterServidorPorId((long)id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        private ActionResult GravarServidor(Servidor servidor)
        {
            try
            {
                    servidorServico.GravarServidor(servidor);
                    return RedirectToAction("ConsultarServidor");
            }
            catch
            {
                return View(servidor);
            }
        }

        // GET: Servidor/Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConsultarServidor()
        {
            return View(servidorServico.ObterCategoriasClassificadasPorNome());
        }

        // GET: Servidor/Create
        //public ActionResult AdicionarServidor()
        //{
        //    return View();
        //}

        // POST: Servidor/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdicionarServidor(Servidor servidor)
        {
            return GravarServidor(servidor);
        }

        //[HttpPost]
        //public string Adicionar(Servidor servidor)
        //{
        //    if (servidor != null)
        //    {
        //        //TODO: salvar dados no banco de dados
        //        GravarServidor(servidor);
        //        return "Obrigado. O dados foram Salvos.";
        //    }
        //    else
        //    {
        //        return "Complete a informação do formulário.";
        //    }
        //}


        //	GET: Servidor/Edit
        [HttpGet]
        public ActionResult EditarServidor(long? id)
        {
            return ObterVisaoServidorPorId(id);
        }

        // POST: Servidor/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarServidor(Servidor servidor)
        {
            return GravarServidor(servidor);
        }

        //	GET:	Servidor/Details
        [HttpGet]
        public ActionResult DetalharServidor(long? id)
        {
            return ObterVisaoServidorPorId(id);
        }

        //	GET:	Servidor/Delete
        [HttpGet]
        public ActionResult DeletarServidor(long? id)
        {
            return ObterVisaoServidorPorId(id);
        }

        //	POST:	Servidor/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletarServidor(long id)
        {
            try
            {
                Servidor servidor = servidorServico.EliminarServidorPorId(id);
                TempData["Message"] = "Servidor " + servidor.Nome
                + " foi removido";
                return RedirectToAction("ConsultarServidor");
            }
            catch
            {
                return View();
            }
        }
    }
}

COO/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section	Styles	{
    <link href="~/Content/css/Dashboard/index.css" rel="stylesheet" />
}

<div class="col-6 col-md-4 col-xl-2">
    <a class="block block-link-shadow text-center" href="@Url.Action("ConsultarOcorrencia","Ocorrencia")">
        <div class="block-content ribbon ribbon-bookmark ribbon-primary ribbon-left" id="qtdOcorrencia">
            <div class="ribbon-box">@ViewBag.QtdOcorrencias</div>
            <p class="mt-5">
                <i class="si si-bubbles fa-3x"></i>
            </p>
            <p class="font-w600">Ocorrências</p>
        </div>
    </a>
</div>

@section	ScriptPage	{
    <script src="~/Scripts/Views/Dashboard/Index.js"></script>
}

COO/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

COO/Views/Ocorrencia/AdicionarOcorrencia.cshtml
@model Modelo.Entidades.Ocorrencia

@{
    ViewBag.Title = "AdicionarOcorrencia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdicionarOcorrencia</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ocorrencia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CriticidadeOcorrencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.CriticidadeOcorrencia, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CriticidadeOcorrencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Solucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Solucao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Solucao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

COO/Views/Ocorrencia/DetalharOcorrencia.cshtml
@model Modelo.Entidades.Ocorrencia

@{
    ViewBag.Title = "DetalharOcorrencia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section	Styles	{
    <link href="~/Template/assets/js/plugins/summernote/summernote-bs4.css" rel="stylesheet" />
}

@Html.HiddenFor(model => model.OcorrenciaId, new { id = "hddnOcorrenciaId" })

<div class="col-lg-12 px-0">
    <!-- Bold -->
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">Informações da Ocorrência</h3>
        </div>
        <div class="row">
            <div class="col-md-6 col-xl-3">
                <a class="block block-link-shadow">
                    <div class="block-content block-content-full">
                        <div class="font-size-h5 font-w700">@Html.DisplayFor(model => model.NumeroOcorrencia)</div>
                        <div class="font-size-sm font-w600 text-uppercase text-muted">
                            @Html.DisplayNameFor(model => model.NumeroOcorrencia)
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-md-6 col-xl-3">
                <a class="block block-link-shadow">
                    <div class="block-content block-content-full">
                        <div class="font-size-h5 font-w700">@Html.DisplayFor(model => model.Titulo)</div>
                        <div class="font-size-sm font-w600 text-uppercase text-muted">@Html.DisplayNameFor(model => model.Titulo)</div>
                    </div>
                </a>
            </div>

            <div class="col-md-6 col-xl-3">
                <a class="block block-link-shadow">
                    <div class="block-content block-content-full">
                        <div class="font-size-h5 font-w700">@Html.DisplayFor(model => model.DataHora)</div>
                        <div class="font-size-sm font-w600 text-uppercase text-muted">@Html.DisplayNameFor(model => model.DataHora)</div>
                    </div>
                </a>
            </div>

            <div class="col-md-6 col-xl-3">
                <a class="block block-link-shadow">
                    <div class="block-content block-content-full">
                        <div class="font-size-h5 font-w700">@Html.DisplayFor(model => model.CriticidadeOcorrencia)</div>
                        <div class="font-size-sm font-w600 text-uppercase text-muted">@Html.DisplayNameFor(model => model.CriticidadeOcorrencia)</div>
                    </div>
                </a>
            </div>

        </div>
    </div>
    <!-- END Bold -->
</div>

<div class="row">
    <div class="col-8">
        <div class="block">
            <div class="block-header block-header-default">
                <h3 class="block-title">Full Editor</h3>
            </div>
            <div class="block-content block-content-full">
                <!-- Summernote Container -->
                <div class="js-summernote"></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-2">
        <button type="button" id="btn-salvar-oc"  class="btn btn-square btn-success min-width-125 mb-10">Enviar</button>
    </div>
</div>

@section	ScriptPage	{
    <script src="~/Template/assets/js/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="~/Scripts/Views/Ocorrencia/DetalharOcorrencia.js"></script>
}

COO/Views/Servidor/AdicionarServidor.cshtml
@model Modelo.Entidades.Servidor

@{
    ViewBag.Title = "AdicionarServidor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col-md-6 offset-md-3 mt-50">
        <div class="block">
            <div class="block-header block-header-default">
                <h3 class="block-title">Novo Servidor</h3>
            </div>
            <div class="block-content">
                <div class="form-group row">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-6" })
                    @Html.LabelFor(model => model.ServidorIp, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.ServidorIp, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ServidorIp, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.AmbienteServidor, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-12">
                        @Html.EnumDropDownListFor(model => model.AmbienteServidor, "Selecionar Ambiente do Servidor", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.AmbienteServidor, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Servicos, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Servicos, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Servicos, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-12">
                        @*<textarea class="form-control" id="example-textarea-input" name="example-textarea-input" rows="6" placeholder="Content.."></textarea>*@
                        @Html.TextAreaFor(model => model.Observacao, new { @size = 10, @class = "form-control" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success pull-right">Salvar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section	ScriptPage	{
    <script src="@Url.Content("~/Scripts/Views/Servidor/AdicionarServidor.js")"></script>
}

COO/Views/Servidor/ConsultarServidor.cshtml
@model IEnumerable<Modelo.Entidades.Servidor>

@{
    ViewBag.Title = "ConsultarServidor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section	Styles	{
    <link href="@Url.Content("~/Template/assets/js/plugins/datatables/dataTables.bootstrap4.css")" rel="stylesheet" />
}
<!-- Dynamic Table Full -->
<div class="block">
    <div class="block-header block-header-default">
        <h2 class="block-title">Lista de Servidores<small></small></h2>
        <button type="button" class="btn btn-circle btn-dual-secondary" data-toggle="layout" data-action="side_overlay_toggle">
            <i class="far fa-plus-square"></i>
        </button>
    </div>
    <div class="block-content block-content-full">
        <!-- DataTables functionality is initialized with .js-dataTable-full class in js/pages/be_tables_datatables.min.js which was auto compiled from _es6/pages/be_tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
            <thead>
                <tr role="row">
                    <th class="text-center sorting_asc" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" aria-sort="ascending" aria-label=": activate to sort column descending" style="width: 10%;">@Html.DisplayNameFor(model => model.ServidorId)</th>
                    <th class="sorting" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">@Html.DisplayNameFor(model => model.Nome)</th>
                    <th class="d-none d-sm-table-cell sorting" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">@Html.DisplayNameFor(model => model.ServidorIp)</th>
                    <th class="d-none d-sm-table-cell sorting" style="width: 15%;" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" aria-label="Access: activate to sort column ascending">@Html.DisplayNameFor(model => model.AmbienteServidor)</th>
                    <th class="text-center sorting_disabled" style="width: 15%;" rowspan="1" colspan="1" aria-label="Profile">Profile</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr role="row" class="odd">
                        <td class="text-center sorting_1">@Html.DisplayFor(modelItem => item.ServidorId)</td>
                        <td class="font-w600">@Html.DisplayFor(modelItem => item.Nome)</td>
                        <td class="d-none d-sm-table-cell">@Html.DisplayFor(modelItem => item.ServidorIp)</td>
                        <td class="d-none d-sm-table-cell">
                            <span class="badge badge-warning">@Html.DisplayFor(modelItem => item.AmbienteServidor)</span>
                        </td>
                        <td class="text-center">
                            @Html.ActionLink("Edit", "Edit", new { id = item.ServidorId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.ServidorId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ServidorId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <aside id="side-overlay" data-simplebar="init">
        <div class="simplebar-track vertical" style="visibility: visible;"><div class="simplebar-scrollbar" style="visibility: visible; top: 0px; height: 220px;"></div></div><div class="simplebar-track horizontal" style="visibility: hidden;"><div class="simplebar-scrollbar"></div></div><div class="simplebar-scroll-content" style="padding-right: 17px; margin-bottom: -34px;">
            <div class="simplebar-content" style="padding-bottom: 17px; margin-right: -17px;">
                <!-- Side Header -->
                <div class="content-header content-header-fullrow">
                    <div class="content-header-section align-parent">
                        <!-- Close Side Overlay -->
                        <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                        <button type="button" class="btn btn-circle btn-dual-secondary align-v-r" data-toggle="layout" data-action="side_overlay_close">
                            <i class="fa fa-times text-danger"></i>
                        </button>
                        <!-- END Close Side Overlay -->
                        <!-- User Info -->
                        <div class="content-header-item">
                            <a class="align-middle link-effect text-primary-dark font-w600">Novo Servidor</a>
                        </div>
                        <!-- END User Info -->
                    </div>
                </div>
                <!-- END Side Header -->
                <!-- Side Content -->
                <div class="content-side">
                    <div class="block-content">
                        <form action="be_pages_dashboard.html" method="post" onsubmit="return false;">
                            <div class="form-group">
                                <label for="example-input-small">Nome Servidor</label>
                                <input type="text" class="form-control form-control-sm  txtNome" id="example-input-small" name="example-input-small" placeholder=".form-control-sm">
                            </div>
                            <div class="form-group">
                                <label for="example-input-small">IP do Servidor</label>
                                <input type="text" class="form-control form-control-sm txtIp" id="example-input-small " name="example-input-small" placeholder=".form-control-sm">
                            </div>

                            <div class="form-group">
                                <label for="example-input-small">Ambiente</label>
                                <select class="form-control form-control-sm" id="rblAmbiente">
                                    <option>Selecione</option>
                                    <option value="0">RJ1</option>
                                    <option value="1">RJ2</option>
                                    <option value="2">MRJ</option>
                                    <option value="3">MSP</option>
                                </select>
                            </div>

                            <div class="form-group row">
                                <label class="col-12" for="example-textarea-input">Observações</label>
                                <div class="col-12">
                                    <textarea class="form-control txtObservacao" id="example-textarea-input " name="example-textarea-input" rows="6" placeholder="Content.."></textarea>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-6">
                                    <button type="submit" class="btn btn-block btn-alt-primary" id="btnSalvar">
                                        <i class="fa fa-refresh mr-5"></i> Salvar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END Side Content -->
            </div>
        </div>
    </aside>
</div>
<!-- END Dynamic Table Full -->

@section	ScriptPage	{
    <script src="@Url.Content("~/Template/assets/js/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/plugins/datatables/dataTables.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/pages/be_tables_datatables.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Views/Servidor/ConsultarServidor.js")"></script>
}

COO/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="pt-br" class="no-focus">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    @RenderSection("styles", false)

    <!-- Icons -->
    <link rel="shortcut icon" href="/assets/media/favicons/favicon.png">
    <link rel="icon" type="image/png" sizes="192x192" href="Template/assets/media/favicons/favicon-192x192.png">
    <link rel="apple-touch-icon" sizes="180x180" href="Template/assets/media/favicons/apple-touch-icon-180x180.png">
    <link href="~/Template/assets/fonts/fontawesome 5.3/css/fontawesome-all.min.css" rel="stylesheet" />
    <!-- END Icons -->
    <!-- Stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,400i,600,700">
    <link rel="stylesheet" id="css-main" href="@Url.Content("~/Template/assets/css/codebase.min.css")">
    <!-- END Stylesheets -->
</head>
<body>
    <div id="page-container" class="sidebar-inverse side-scroll page-header-fixed page-header-inverse main-content-boxed">
        <!-- Header -->
        <header id="page-header">
            <!-- Header Content -->
            <div class="content-header">
                <!-- Left Section -->
                <div class="content-header-section">
                    <!-- Logo -->
                    <div class="content-header-item">
                        @*<a class=" font-w700 mr-5" href="@Url.Action("Index","Home")">
                                <img src="~/Content/img/blacklogo.png" />
                            </a>*@
                    </div>
                    <!-- END Logo -->
                </div>
                <!-- END Left Section -->
                <!-- Middle Section -->
                <div class="content-header-section d-none d-lg-block">
                    <!-- Header Navigation -->
                    <ul class="nav-main-header">
                        <li>
                            <a href="@Url.Action("Index","Dashboard")"><i class="si si-compass"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarCheckList","CheckList")"><i class="fas fa-check-square"></i>CheckList</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarOcorrencia","Ocorrencia")"><i class="fas fa-exclamation-triangle"></i>Ocorrências</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarServidor","Servidor")"><i class="fas fa-server"></i>Servidores</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ConsultarContato","Contato")"><i class="fas fa-phone-square"></i>Contatos</a>
                        </li>
                    </ul>
                    <!-- END Header Navigation -->
                </div>
                <!-- Right Section -->
                <div class="content-header-section">
                    <!-- Color Themes + A few of the many header options (used just for demonstration) -->
                    <!-- Themes functionality initialized in Template._uiHandleTheme() -->
                    <!-- END Color Themes + A few of the many header options -->
                    <!-- Open Search Section -->
                    <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                    <!-- END Open Search Section -->
                    <!-- Toggle Sidebar -->
                    <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                    <!-- END Toggle Sidebar -->
                </div>
                <!-- END Right Section -->
            </div>
            <!-- END Header Content -->
            <!-- Header Search -->
            <!-- END Header Search -->
            <!-- Header Loader -->
            <!-- Please check out the Activity page under Elements category to see examples of showing/hiding it -->
            <div id="page-header-loader" class="overlay-header bg-primary">
                <div class="content-header content-header-fullrow text-center">
                    <div class="content-header-item">
                        <i class="fa fa-sun-o fa-spin text-white"></i>
                    </div>
                </div>
            </div>
            <!-- END Header Loader -->
        </header>
        <!-- END Header -->
        <!-- Main Container -->
        <main id="main-container">
            @RenderBody()
            <!-- Page Content -->
            <!-- END Page Content -->

        </main>
        <!-- END Main Container -->
        <!-- Footer -->
        @*<footer id="page-footer" class="opacity-0">
                <div class="content py-20 font-size-xs clearfix">
                    <div class="float-right">
                        Crafted with <i class="fa fa-heart text-pulse"></i> by <a class="font-w600" href="https://1.envato.market/ydb" target="_blank">pixelcave</a>
                    </div>
                    <div class="float-left">
                        <a class="font-w600" href="#" target="_blank">Codebase 3.0</a> &copy; <span class="js-year-copy">2017</span>
                    </div>
                </div>
            </footer>*@
        <!-- END Footer -->
    </div>
    <!-- END Page Container -->
    <!-- Page JS Plugins -->
    <script src="@Url.Content("~/Scripts/jquery-3.4.1.min.js")"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @*<script src="@Url.Content("~/Template/assets/js/plugins/chartjs/Chart.bundle.min.js")"></script>*@

    <!-- Page JS Code -->
    <script src="@Url.Content("~/Template/assets/js/codebase.core.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/codebase.app.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/pages/be_pages_dashboard.min.js")"></script>
    <script src="@Url.Content("~/Template/assets/js/plugins/chartjs/Chart.min.js")"></script>

    @RenderSection("ScriptPage", false);
</body>
</html>